googleapis/nodejs-compute

system-test/compute.js
Stops a system test failure I somehow missed.
=> Use 10 GB instances, the minimum.

.circleci/config.yml, package.json, samples/package.json, src/image.js, src/index.js, system-test/compute.js, test/image.js, test/index.js
Probably the function fits better in a different scope? On the other hand the path '/global/images' matches in project scope intrinsically.
Fixes #<issue_number_goes_here> (it's a good idea to open an issue first for discussion)
It's probably quicker to start a discussion from this PR?
- [(*)] Tests and linter pass
no new issues introduced, already on master: 6 problems (6 errors, 0 warnings)
no tests have yet been added
- [*] Appropriate docs were updated (if necessary)
=> Call for creating an image from a disk

src/snapshot.js, system-test/compute.js, test/snapshot.js
Fixes #66 
The Snapshot API endpoint doesn't follow the typical hierarchy we anticipated: https://cloud.google.com/compute/docs/reference/rest/v1/snapshots/get
=> Use correct URI for Snapshot instances

.cloud-repo-tools.json, CONTRIBUTORS, README.md, package.json, samples/README.md
Do not list this sample in the README as it is for googleapi, not
@google-cloud.
Keep the example source code because it is
referenced [here](https://cloud.google.com/compute/docs/tutorials/nodejs-guide).
/cc @jmdobry
=> Do not show sample for Google API Client library

samples/startup-script/package.json
Fixes https://github.com/googleapis/nodejs-compute/issues/82. 
Use 600 seconds like the other system tests. Otherweise CI fails https://circleci.com/gh/googleapis/nodejs-compute/2040
=> Increase timeout in startup sample test

samples/startup-script/index.js
Made the test more robust. Callbacks could already be queued before the first successful ping is executed. I can reproduce this locally with a lower timeout and this fixes it.
https://circleci.com/gh/googleapis/nodejs-compute/2068
=> Fix problem with multiple deletes in test

.circleci/config.yml
For some reason this repo still had Circle running as root which broke `npm link` and `npm install` in samples in some weird random way. Fixing that.
=> chore: run circle as non-root, fix npm link

package-lock.json, samples/package-lock.json, samples/startup-script/index.js
Fix `eslint` error in startup-script sample. 
Fixes https://circleci.com/gh/googleapis/nodejs-compute/2294.
=> Update eslint and fix formatting

samples/mailjet.js, samples/package-lock.json, samples/package.json, samples/sendgrid.js, samples/test/.eslintrc.yml, samples/test/mailjet.test.js, samples/test/sendgrid.test.js
Mostly a revert of 518d762fb001e230e5fbd2638bbaa45f77858c2d
Samples are needed for pages in the documentation.
=> Add mailjet and sendgrid back in

system-test/compute.js, test/address.js, test/autoscaler.js, test/disk.js, test/firewall.js, test/health-check.js, test/index.js, test/instance-group.js, test/machine-type.js, test/network.js, test/operation.js, test/region.js, test/rule.js, test/service.js, test/snapshot.js, test/subnetwork.js, test/vm.js, test/zone.js
deepEqual is deprecated. Use deepStrictEqual instead
=> chore: assert.deelEqual => assert.deepStrictEqual

src/vm.js, system-test/compute.js, test/vm.js
This changes the default behavior from `POST` to `PATCH` so that the custom metadata passed into `VM#setMetadata` augments what is already set.
Fixes #168
=> Use PATCH semantics by default to set custom metadata

src/disk.js, src/index.js, src/instance-group.js, src/network.js, src/region.js, src/vm.js, src/zone.js, test/address.js, test/autoscaler.js, test/disk.js, test/firewall.js, test/health-check.js, test/image.js, test/index.js, test/instance-group.js, test/network.js, test/operation.js, test/project.js, test/region.js, test/rule.js, test/service.js, test/snapshot.js, test/subnetwork.js, test/vm.js, test/zone.js
Just swaps `extend` for the native `Object.assign` where possible.
=> refactor: use Object.assign where possible

src/snapshot.js, system-test/compute.js, test/snapshot.js
also modified the related test case
Fixes #250
=> fix: snapshot.delete() throws issue

src/instance-group-manager.js, src/instance-group.js, test/instance-group-manager.js
=> Adds getManagedInstances and deleteInstances to InstanceGroupManger API

src/instance-group-manager.js, test/instance-group-manager.js
=> feat: Adds abandonInstances to InstanceGroupManger API

src/zone.js
Document the proper object structure accepted by `zone.createVM`, fixes #107.
=> fix(docs): document correct object structure for zone.createVM

system-test/compute.js
System tests started failing because of this new field added to the output.
=> test: fix autoscaler system tests

package.json, src/address.js, src/autoscaler.js, src/disk.js, src/firewall.js, src/health-check.js, src/image.js, src/index.js, src/instance-group-manager.js, src/instance-group.js, src/machine-type.js, src/network.js, src/operation.js, src/project.js, src/region.js, src/rule.js, src/service.js, src/snapshot.js, src/subnetwork.js, src/vm.js, src/zone.js, test/address.js, test/instance-group-manager.js, test/instance-group.js, test/machine-type.js, test/operation.js, test/subnetwork.js
Allows `pollIntervalMs` to be configured for long running operations, when instantiating a `Compute` instance:
```js
new Compute({
pollIntervalMs: 2000
})
```
=> feat: allow pollIntervalMs to be configured

samples/test/samples.test.js, system-test/compute.js
I'm seeing:
```
Error: The network resource 'projects/long-door-651/global/networks/gcloud-7cb2678f-network-87525255' is already being used by 'projects/long-door-651/global/firewalls/gcloud-7cb2678f-network-87525255-wxdqry2w4crjze2quc4w4di6'
```
Periodically in the logs, sometimes for the `before` action, and sometimes for the `after`, making me think the cleanup logic is sometimes flaky.
=> test: cleanup logic causes errors

package.json
">10"` range does not include the v10 version (currently still LTS),  it eforces v11 and up.
Switching to `">=10"` to include v10, which I believe was the original intent (changelog: "require node 10 in engines field")
Fixes #450 🦕
=> fix: correct engines range to include node v10
